const fs = require('fs');
const path = require('path');

const KAMUS_DIR = path.join(__dirname, '../assets/kamus');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/imageMap.ts');

function generateImageMap() {
  console.log('🔄 Scanning image files in assets/kamus...');
  
  // Ensure directories exist
  if (!fs.existsSync(KAMUS_DIR)) {
    fs.mkdirSync(KAMUS_DIR, { recursive: true });
  }
  
  const categories = ['pria', 'wanita', 'umum'];
  categories.forEach(folder => {
    const p = path.join(KAMUS_DIR, folder);
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
  });

  const mapping = {};

  categories.forEach(category => {
    const categoryPath = path.join(KAMUS_DIR, category);
    if (!fs.existsSync(categoryPath)) return;

    const files = fs.readdirSync(categoryPath).filter(f => f.match(/\.(png|jpg|jpeg)$/i));
    files.forEach(file => {
      const key = `${category}_${file}`;
      mapping[key] = `../../assets/kamus/${category}/${file}`;
    });
  });

  let fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.\n`;
  fileContent += `// This file is generated by scripts/sync-images.js\n\n`;
  fileContent += `const imageMap: Record<string, any> = {\n`;
  
  for (const [key, relPath] of Object.entries(mapping)) {
    fileContent += `  '${key}': require('${relPath}'),\n`;
  }
  
  fileContent += `};\n\n`;
  
  // Create a helper function to resolve image based on gender
  fileContent += `export const getLocalImage = (filename: string, gender?: 'boy' | 'girl' | null) => {\n`;
  fileContent += `  // Fallbacks: 1. gender folder, 2. umum folder\n`;
  fileContent += `  const prefix = gender === 'boy' ? 'pria' : (gender === 'girl' ? 'wanita' : 'umum');\n`;
  fileContent += `  if (imageMap[\`\${prefix}_\${filename}\`]) return imageMap[\`\${prefix}_\${filename}\`];\n`;
  fileContent += `  if (imageMap[\`umum_\${filename}\`]) return imageMap[\`umum_\${filename}\`];\n`;
  fileContent += `  // If still not found, return undefined so caller can handle placeholder\n`;
  fileContent += `  return undefined;\n`;
  fileContent += `};\n`;

  // Create src/assets if it doesn't exist
  const srcAssetsDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(srcAssetsDir)) {
    fs.mkdirSync(srcAssetsDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ imageMap.ts generated with ${Object.keys(mapping).length} local images mapped!`);
}

generateImageMap();
