const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, '../assets/audio');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/audioMap.ts');

// Language folders sit one level above profile folders:
//   assets/audio/{profile}/{word}.mp3            → key "{word}_{profile}"     (Indonesian recordings, flat/legacy layout)
//   assets/audio/{lang}/{profile}/{word}.mp3     → key "{word}_{profile}_{lang}"
const LANG_FOLDERS = ['id', 'en', 'zh'];
const PROFILES = ['ayah', 'ibu', 'pria', 'wanita'];

function scanProfileDir(profilePath, keyPrefix) {
  const mapping = {};
  if (!fs.existsSync(profilePath)) return mapping;
  const files = fs.readdirSync(profilePath).filter(f => f.endsWith('.mp3') || f.endsWith('.wav'));
  files.forEach(file => {
    const word = path.basename(file, path.extname(file)); // "Saya"
    const relFrom = path.relative(path.dirname(OUTPUT_FILE), path.join(profilePath, file)).split(path.sep).join('/');
    mapping[`${word}${keyPrefix}`] = relFrom;
  });
  return mapping;
}

function generateAudioMap() {
  console.log('🔄 Scanning audio files in assets/audio...');

  if (!fs.existsSync(AUDIO_DIR)) {
    fs.mkdirSync(AUDIO_DIR, { recursive: true });
    // Create subfolders
    PROFILES.forEach(folder => {
      fs.mkdirSync(path.join(AUDIO_DIR, folder), { recursive: true });
    });
  }

  const mapping = {};

  // Flat/legacy layout: assets/audio/{profile}/{word}.mp3 (implicit Indonesian 'id')
  PROFILES.forEach(profile => {
    Object.assign(mapping, scanProfileDir(path.join(AUDIO_DIR, profile), `_${profile}`));
  });

  // Language-aware layout: assets/audio/{lang}/{profile}/{word}.mp3
  LANG_FOLDERS.forEach(lang => {
    PROFILES.forEach(profile => {
      Object.assign(
        mapping,
        scanProfileDir(path.join(AUDIO_DIR, lang, profile), `_${profile}_${lang}`)
      );
    });
  });

  let fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.\n`;
  fileContent += `// This file is generated by scripts/sync-audio.js\n`;
  fileContent += `// Keys: "{word}_{profile}" (legacy flat layout) and "{word}_{profile}_{lang}".\n`;
  fileContent += `// Profiles: ayah (dad) / ibu (mom) / pria (male child) / wanita (female child).\n\n`;
  fileContent += `export const localAudioMap: Record<string, any> = {\n`;

  for (const [key, relPath] of Object.entries(mapping)) {
    // Escape string just in case
    fileContent += `  '${key}': require('${relPath}'),\n`;
  }

  fileContent += `};\n`;

  // Create src/assets if it doesn't exist
  const srcAssetsDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(srcAssetsDir)) {
    fs.mkdirSync(srcAssetsDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ audioMap.ts generated with ${Object.keys(mapping).length} local audio files mapped!`);
}

generateAudioMap();
