const fs = require('fs');
const path = require('path');

const AUDIO_DIR = path.join(__dirname, '../assets/audio');
const OUTPUT_FILE = path.join(__dirname, '../src/assets/audioMap.ts');

function generateAudioMap() {
  console.log('🔄 Scanning audio files in assets/audio...');
  
  if (!fs.existsSync(AUDIO_DIR)) {
    fs.mkdirSync(AUDIO_DIR, { recursive: true });
    // Create subfolders
    ['ayah', 'ibu', 'pria', 'wanita'].forEach(folder => {
      fs.mkdirSync(path.join(AUDIO_DIR, folder), { recursive: true });
    });
  }

  const profiles = ['ayah', 'ibu', 'pria', 'wanita'];
  const mapping = {};

  profiles.forEach(profile => {
    const profilePath = path.join(AUDIO_DIR, profile);
    if (!fs.existsSync(profilePath)) return;

    const files = fs.readdirSync(profilePath).filter(f => f.endsWith('.mp3') || f.endsWith('.wav'));
    files.forEach(file => {
      const word = path.basename(file, path.extname(file)); // "Saya"
      const key = `${word}_${profile}`;
      mapping[key] = `../../assets/audio/${profile}/${file}`;
    });
  });

  let fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.\n`;
  fileContent += `// This file is generated by scripts/sync-audio.js\n\n`;
  fileContent += `export const localAudioMap: Record<string, any> = {\n`;
  
  for (const [key, relPath] of Object.entries(mapping)) {
    // Escape string just in case
    fileContent += `  '${key}': require('${relPath}'),\n`;
  }
  
  fileContent += `};\n`;

  // Create src/assets if it doesn't exist
  const srcAssetsDir = path.dirname(OUTPUT_FILE);
  if (!fs.existsSync(srcAssetsDir)) {
    fs.mkdirSync(srcAssetsDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`✅ audioMap.ts generated with ${Object.keys(mapping).length} local audio files mapped!`);
}

generateAudioMap();
