// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// This file is generated by scripts/sync-audio.js
// Keys: "{word}_{profile}" (legacy flat layout) and "{word}_{profile}_{lang}".
// Profiles: ayah (dad) / ibu (mom) / pria (male child) / wanita (female child).

export const localAudioMap: Record<string, any> = {
  'Oke_ayah': require('../../assets/audio/ayah/Oke.mp3'),
  'Tunggu Sebentar_ayah': require('../../assets/audio/ayah/Tunggu Sebentar.mp3'),
  'Oke_ibu': require('../../assets/audio/ibu/Oke.mp3'),
  'Oke2_ibu': require('../../assets/audio/ibu/Oke2.mp3'),
  'Tunggu Sebentar_ibu': require('../../assets/audio/ibu/Tunggu Sebentar.mp3'),
  'Tunggu Sebentar2_ibu': require('../../assets/audio/ibu/Tunggu Sebentar2.mp3'),
};
