// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// This file is generated by scripts/sync-images.js

const imageMap: Record<string, any> = {
  'pria_ayah.png': require('../../assets/kamus/pria/ayah.png'),
  'pria_bagus.png': require('../../assets/kamus/pria/bagus.png'),
  'pria_berhenti.png': require('../../assets/kamus/pria/berhenti.png'),
  'pria_dia.png': require('../../assets/kamus/pria/dia.png'),
  'pria_ibu.png': require('../../assets/kamus/pria/ibu.png'),
  'pria_kami.png': require('../../assets/kamus/pria/kami.png'),
  'pria_kamu.png': require('../../assets/kamus/pria/kamu.png'),
  'pria_keluarga.png': require('../../assets/kamus/pria/keluarga.png'),
  'pria_lagi.png': require('../../assets/kamus/pria/lagi.png'),
  'pria_main.png': require('../../assets/kamus/pria/main.png'),
  'pria_makan.png': require('../../assets/kamus/pria/makan.png'),
  'pria_mau.png': require('../../assets/kamus/pria/mau.png'),
  'pria_mereka.png': require('../../assets/kamus/pria/mereka.png'),
  'pria_minum.png': require('../../assets/kamus/pria/minum.png'),
  'pria_sakit.png': require('../../assets/kamus/pria/sakit.png'),
  'pria_saya.png': require('../../assets/kamus/pria/saya.png'),
  'pria_selesai.png': require('../../assets/kamus/pria/selesai.png'),
  'pria_suka.png': require('../../assets/kamus/pria/suka.png'),
  'pria_tidak.png': require('../../assets/kamus/pria/tidak.png'),
  'pria_tidur.png': require('../../assets/kamus/pria/tidur.png'),
  'pria_tolong.png': require('../../assets/kamus/pria/tolong.png'),
  'pria_ya.png': require('../../assets/kamus/pria/ya.png'),
  'wanita_ayah.png': require('../../assets/kamus/wanita/ayah.png'),
  'wanita_bagus.png': require('../../assets/kamus/wanita/bagus.png'),
  'wanita_berhenti.png': require('../../assets/kamus/wanita/berhenti.png'),
  'wanita_dia.png': require('../../assets/kamus/wanita/dia.png'),
  'wanita_ibu.png': require('../../assets/kamus/wanita/ibu.png'),
  'wanita_kami.png': require('../../assets/kamus/wanita/kami.png'),
  'wanita_kamu.png': require('../../assets/kamus/wanita/kamu.png'),
  'wanita_keluarga.png': require('../../assets/kamus/wanita/keluarga.png'),
  'wanita_lagi.png': require('../../assets/kamus/wanita/lagi.png'),
  'wanita_main.png': require('../../assets/kamus/wanita/main.png'),
  'wanita_makan.png': require('../../assets/kamus/wanita/makan.png'),
  'wanita_mau.png': require('../../assets/kamus/wanita/mau.png'),
  'wanita_mereka.png': require('../../assets/kamus/wanita/mereka.png'),
  'wanita_minum.png': require('../../assets/kamus/wanita/minum.png'),
  'wanita_sakit.png': require('../../assets/kamus/wanita/sakit.png'),
  'wanita_saya.png': require('../../assets/kamus/wanita/saya.png'),
  'wanita_selesai.png': require('../../assets/kamus/wanita/selesai.png'),
  'wanita_suka.png': require('../../assets/kamus/wanita/suka.png'),
  'wanita_tidak.png': require('../../assets/kamus/wanita/tidak.png'),
  'wanita_tidur.png': require('../../assets/kamus/wanita/tidur.png'),
  'wanita_tolong.png': require('../../assets/kamus/wanita/tolong.png'),
  'wanita_ya.png': require('../../assets/kamus/wanita/ya.png'),
  'umum_toilet.png': require('../../assets/kamus/umum/toilet.png'),
};

export const getLocalImage = (filename: string, gender?: 'boy' | 'girl' | null) => {
  // Fallbacks: 1. gender folder, 2. umum folder
  const prefix = gender === 'boy' ? 'pria' : (gender === 'girl' ? 'wanita' : 'umum');
  if (imageMap[`${prefix}_${filename}`]) return imageMap[`${prefix}_${filename}`];
  if (imageMap[`umum_${filename}`]) return imageMap[`umum_${filename}`];
  // If still not found, return undefined so caller can handle placeholder
  return undefined;
};
